config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users do
    resources :shows, path: 'live' do
      resource :image_upload, only: [:edit, :create, :destroy]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/show.rb
class Show < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  scope :publish, -> { where(published: true) }

  def json_obj
    {
      title: title,
      body: body,
      day: I18n.l(day),
      place: place,
      img: img
    }
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :shows, dependent: :destroy
  validates :name, presence: true, uniqueness: true
  validates :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def set_user
    @user = User.find_by(name: params[:user_id]) || User.find(params[:user_id])
  end

  def basic_auth
    authenticate_or_request_with_http_basic do |user, pass|
      user == @user.name && @user.authenticate(pass)
    end
  end

end

app/controllers/image_uploads_controller.rb
class ImageUploadsController < ApplicationController
  before_action :set_user, :set_show
  before_action :basic_auth

  def edit
    if params[:preview]
      url = url_for(@show.image) if @show.image.attached?
      render :json, url
    else
      render
    end
  end

  def create
    @show.image.attach(params.require(:image))
    flash[:notice] = '画像を保存しました'
    redirect_to user_shows_path(@user)
  end

  def destroy
    @show.image.purge_later
    flash[:notice] = '画像を削除しました'
    redirect_to user_shows_path(@user)
  end

  private

  def set_show
    @show = Show.find(params[:show_id])
  end
end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
  before_action :set_user
  before_action :basic_auth, except: [:index, :show] # TODO: remove later
  before_action :set_show, only: [:show, :edit, :update, :destroy]

  protect_from_forgery except: :index # TODO: think

  # GET /shows
  # GET /shows.json
  def index
    @shows = Show.where(user: @user).order(day: :desc).all
    respond_to do |format|
      format.html { render :index }
      format.json { render json: @shows.map(&:json_obj), callback: callback_param }
    end
  end

  # GET /shows/1
  # GET /shows/1.json
  def show
    respond_to do |format|
      format.html { render :show }
      format.json { render json: @show.json_obj }
    end
  end

  # GET /shows/new
  def new
    @show = @user.shows.build
  end

  # GET /shows/1/edit
  def edit
  end

  # POST /shows
  # POST /shows.json
  def create
    @show = Show.new(show_params)

    respond_to do |format|
      if @show.save
        format.html { redirect_to user_shows_path(@user), notice: 'Show was successfully created.' }
        format.json { render :show, status: :created, location: @show }
      else
        format.html { render :new }
        format.json { render json: @show.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shows/1
  # PATCH/PUT /shows/1.json
  def update
    respond_to do |format|
      if @show.update(show_params)
        format.html { redirect_to user_shows_path(@user), notice: 'Show was successfully updated.' }
        format.json { render :show, status: :ok, location: @show }
      else
        format.html { render :edit }
        format.json { render json: @show.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shows/1
  # DELETE /shows/1.json
  def destroy
    @show.destroy
    respond_to do |format|
      format.html { redirect_to user_shows_path(@user), notice: 'Show was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_show
      @show = Show.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def show_params
      params.require(:show).permit(:body, :title, :day, :img, :place, :user_id, :published, :image)
    end

    def callback_param
      params[:callback].present? ? params[:callback].gsub(/\W/, '') : nil
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/image_uploads/create.html.haml
%h1 ImageUploads#create
%p Find me in app/views/image_uploads/create.html.haml

app/views/image_uploads/destroy.html.haml
%h1 ImageUploads#destroy
%p Find me in app/views/image_uploads/destroy.html.haml

app/views/image_uploads/edit.html.haml
%h2 Image

= form_with url: user_show_image_upload_path(@user, @show), class: 'pure-form', local: true, method: :post do |f|
  = f.file_field :image
  = f.submit '送信'

= link_to 'Back', user_shows_path(@user)

app/views/image_uploads/update.html.haml
%h1 ImageUploads#update
%p Find me in app/views/image_uploads/update.html.haml

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}/
    %title Scheduleapi
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_pack_tag 'application'
  %body
    #main
      - if notice
        = notice
      - if alert
        = alert
      = yield

app/views/shows/_form.html.haml
= form_with(model: [user, show], local: true, class: 'pure-form') do |form|
  - if show.errors.any?
    #error_explanation
      %h2
        = pluralize(show.errors.count, "error")
        prohibited this show from being saved:
      %ul
        - show.errors.full_messages.each do |message|
          %li= message
  .field
    = form.label :title
    = form.text_field :title
  .field
    = form.label :body
    = form.text_area :body
  .field
    = form.label :day
    = form.date_select :day
  .field
    = form.label :img
    = form.text_field :img
  .field
    = form.label :place
    = form.text_field :place
  .field
    = form.label :published
    = form.check_box :published
  = form.hidden_field :user_id
  .actions
    = form.submit

app/views/shows/edit.html.haml
%h1 Editing Show
= render 'form', show: @show, user: @user
|
= link_to 'Back', user_shows_path(@user)

app/views/shows/index.html.haml
%h1 Live

%h2= @user.name

= link_to 'New live', new_user_show_path

%table.pure-table
  %thead
    %tr
      %th Day
      %th Title
      %th Body
      %th Place
      %th Img
      %th Published
      %th Image
      %th{:colspan => "2"}
  %tbody
    - @shows.each do |show|
      %tr
        %td= show.day
        %td= show.title
        %td= show.body
        %td= show.place
        %td= show.img
        %td= "✔" if show.published?
        %td
          = link_to 'Upload', edit_user_show_image_upload_path(@user, show)
          %br
          = link_to 'Delete', user_show_image_upload_path(@user, show), method: :delete, data: { confirm: 'Are you sure?'}  if show.image.attached?
        %td= link_to 'Edit', edit_user_show_path(@user, show)
        %td= link_to 'Destroy', user_show_path(@user, show), method: :delete, data: { confirm: 'Are you sure?' }
%br/

app/views/shows/new.html.haml
%h1 New Show
= render 'form', show: @show, user: @user
= link_to 'Back', user_shows_path(@user)

app/views/shows/show.html.haml
%p#notice= notice
%p
  %strong Body:
  = @show.body
%p
  %strong Title:
  = @show.title
%p
  %strong Day:
  = @show.day
%p
  %strong Img:
  = @show.img
%p
  %strong Place:
  = @show.place
%p
  %strong User:
  = @show.user_id
= link_to 'Edit', edit_show_path(@show)
|
= link_to 'Back', shows_path

app/views/users/_form.html.haml
= form_with(model: user, local: true) do |form|
  - if user.errors.any?
    #error_explanation
      %h2
        = pluralize(user.errors.count, "error")
        prohibited this user from being saved:
      %ul
        - user.errors.full_messages.each do |message|
          %li= message
  .field
    = form.label :name
    = form.text_field :name, id: :user_name
  .field
    = form.label :password
    = form.password_field :password, id: :user_password
  .field
    = form.label :password_confirmation
    = form.password_field :password_confirmation, id: :user_password_confirmation
  .actions
    = form.submit

app/views/users/edit.html.haml
%h1 Editing User
= render 'form', user: @user
= link_to 'Show', @user
|
= link_to 'Back', users_path

app/views/users/index.html.haml
%p#notice= notice
%h1 Users
%table
  %thead
    %tr
      %th Name
      %th{:colspan => "3"}
  %tbody
    - @users.each do |user|
      %tr
        %td= user.name
        %td= link_to 'Show', user
        %td= link_to 'Edit', edit_user_path(user)
        %td= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New User', new_user_path

app/views/users/new.html.haml
%h1 New User
= render 'form', user: @user
= link_to 'Back', users_path

app/views/users/show.html.haml
%p#notice= notice
%p
  %strong Name:
  = @user.name
= link_to 'Edit', edit_user_path(@user)
|
= link_to 'Back', users_path